---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: node-app
  name: node-app-sv
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: node-app
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: node-app
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-app
    spec:
      containers:
      - image: apwe/node-app:v2
        name: node-app
        ports:
        - containerPort: 3000
        resources: {}
status: {}
